import { StyleSheet } from 'react-native';

// Bir nechta komponent ishlatadigan umumiy stillar.
export const common = StyleSheet.create({
  label: { fontWeight: '700', fontSize: 14.5, marginBottom: 10, marginTop: 18 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: { width: 10, height: 10, borderRadius: 5 },
  hint: { fontSize: 12, marginTop: -6, marginBottom: 12, lineHeight: 16 },
  requirementsBox: {
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 16,
  },
  requirementLabel: { fontSize: 14, fontWeight: '700' },
  requirementSub: { fontSize: 12, marginTop: 2 },
  requirementDivider: { height: 1, marginVertical: 14 },
  addChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  addChipTxt: { fontSize: 13, fontWeight: '600' },
  input: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 50,
    fontSize: 14,
  },
  cta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 54,
    borderRadius: 15,
    gap: 8,
    marginTop: 28,
  },
  ctaTxt: { fontSize: 15, fontWeight: '700' },
  modalTitle: { fontSize: 17, fontWeight: '700' },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
  },
  categoryRowTxt: { fontSize: 14.5, fontWeight: '600', flex: 1 },
  modalDoneBtn: {
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  modalDoneTxt: { color: '#fff', fontSize: 15, fontWeight: '700' },
  mapBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
  },
});
