import { createContext, useContext, useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { useTheme } from '../../context/ThemeContext';
import { POPULAR_TILE_W } from './constants';

// Ekran bo'limlari mavzu (t) va tayyor uslublar (styles) ni shu kontekstdan oladi.
const XizmatlarStyleContext = createContext(null);

export function XizmatlarStyleProvider({ children }) {
  const { theme: t } = useTheme();
  const value = useMemo(() => ({ t, styles: buildStyles(t) }), [t]);
  return <XizmatlarStyleContext.Provider value={value}>{children}</XizmatlarStyleContext.Provider>;
}

export const useXizmatlarStyles = () => useContext(XizmatlarStyleContext);

// ─── Uslublar ──────────────────────────────────────────────────

function buildStyles(t) {
  return StyleSheet.create({
    verifiedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 4,
      marginBottom: 12,
    },
  screen: { flex: 1, backgroundColor: t.bg },
  header: { flexDirection: 'row', gap: 10, padding: 16, paddingBottom: 0 },
  headerEmbedded: { padding: 0 },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: t.inputBg,
    borderRadius: 999,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: t.border,
  },
  searchBoxOnHero: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255,255,255,0.4)',
  },
  searchBoxFocused: {
    borderColor: 'rgba(232,122,69,0.55)',
    backgroundColor: t.card,
  },
  searchInput: {
    flex: 1,
    color: t.text,
    fontSize: 14,
    paddingVertical: 13,
  },
  filterBtn: {
    width: 48,
    height: 48,
    borderRadius: 999,
    backgroundColor: t.inputBg,
    borderWidth: 1.5,
    borderColor: t.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBtnActive: {
    backgroundColor: '#e87a45',
    borderColor: '#e87a45',
    shadowColor: '#e87a45',
    shadowOpacity: 0.45,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  filterBtnOnHero: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255,255,255,0.4)',
  },
  filterBtnActiveOnHero: {
    backgroundColor: '#fff',
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  filterDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3f7fd4',
    borderWidth: 1.5,
    borderColor: t.inputBg,
  },

  filterBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
  filterPanel: {
    margin: 16,
    backgroundColor: t.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: t.border,
    padding: 14,
  },
  filterSectionLabel: {
    color: t.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  chipRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  chipPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
  },
  chipPillActive: { backgroundColor: '#e87a45' },
  chipPillLabel: { color: t.muted, fontSize: 12, fontWeight: '700' },
  chipPillLabelActive: { color: '#fff' },

  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  selectRowDisabled: { opacity: 0.45 },
  selectRowText: { flex: 1, color: t.muted, fontSize: 13, fontWeight: '600' },
  selectRowTextActive: { color: t.text, fontWeight: '700' },

  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: t.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 28,
    maxHeight: '65%',
  },
  sheetTitle: { color: t.text, fontSize: 15, fontWeight: '800', marginBottom: 10 },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: t.border,
  },
  sheetRowText: { color: t.muted, fontSize: 14, fontWeight: '600' },
  sheetRowTextActive: { color: '#e87a45', fontWeight: '800' },
  certRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 12,
    padding: 12,
  },
  certRowActive: { backgroundColor: 'rgba(63,125,212,0.15)' },
  certLabel: { color: t.muted, fontSize: 12.5, fontWeight: '700' },
  certLabelActive: { color: t.blue },
  resetLink: { color: '#e87a45', fontSize: 12, fontWeight: '700', textAlign: 'center' },

  body: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },

  sectionTitle: { color: t.text, fontSize: 20, fontWeight: '800' },
  sectionSubtitle: { color: t.muted, fontSize: 12.5, marginTop: 3, marginBottom: 18 },
  groupLabel: { color: t.text, fontSize: 14.5, fontWeight: '800', marginBottom: 12 },

  popularTile: {
    width: POPULAR_TILE_W,
    alignItems: 'center',
    gap: 8,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 16,
    paddingVertical: 14,
    position: 'relative',
  },

  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  categoryCard: {
    width: '31%',
    alignItems: 'center',
    gap: 8,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 16,
    paddingVertical: 14,
    position: 'relative',
  },
  categoryBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryBadgeText: { color: '#fff', fontSize: 9.5, fontWeight: '800' },
  categoryIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryLabel: { color: t.text, fontSize: 11.5, fontWeight: '700', textAlign: 'center' },

  backBtnDark: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  statCell: { flex: 1, alignItems: 'center' },
  statDivider: { width: 1, height: 26, backgroundColor: t.border },
  statValue: { color: t.text, fontSize: 16, fontWeight: '800' },
  statLabel: {
    color: t.muted,
    fontSize: 9.5,
    fontWeight: '700',
    marginTop: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },

  // ── Yo'nalish hero (doim to'q sarg'ish fon — mavzudan qat'i nazar) ──
  heroShadowWrap: {
    marginHorizontal: -16,
    marginTop: -16,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: '#e87a45',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
  },
  hero: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 34,
    position: 'relative',
    overflow: 'hidden',
  },
  heroWatermark: {
    position: 'absolute',
    right: -20,
    bottom: -30,
    fontSize: 140,
    opacity: 0.14,
    transform: [{ rotate: '-14deg' }],
  },
  heroIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroEyebrow: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 10.5,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heroTitle: { color: '#fff', fontSize: 23, fontWeight: '800', marginTop: 2 },
  heroSubtitle: { color: 'rgba(255,255,255,0.8)', fontSize: 12.5, fontWeight: '600', marginTop: 3 },

  statsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 14,
    marginHorizontal: 12,
    marginTop: -20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 8,
  },

  // ── Usta kartasi ──
  listWrap: { paddingTop: 16, gap: 14 },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 34,
    paddingHorizontal: 16,
    backgroundColor: t.card,
    borderWidth: 1,
    borderColor: t.border,
    borderRadius: 18,
  },
  emptyText: { color: t.muted, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  });
}
